# Generated by Django 5.2.6 on 2025-12-04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_milestones(apps, schema_editor):
    Milestone = apps.get_model("goals", "Milestone")
    milestones = [
        # Total Goals
        ("First Step", "Create your first goal", 1, "total_goals", None),
        ("Getting Serious", "Create 5 goals", 5, "total_goals", None),
        ("Consistency", "Have 10 goals", 10, "total_goals", None),
        ("High Achiever", "Have 20 goals", 20, "total_goals", None),
        ("Goal Crusher", "Have 30 goals", 30, "total_goals", None),
        ("Master of Goals", "Have 50 goals", 50, "total_goals", None),

        # Completed Goals
        ("Finisher", "Complete your first goal", 1, "completed_goals", None),
        ("Achiever", "Complete 5 goals", 5, "completed_goals", None),
        ("Champion", "Complete 10 goals", 10, "completed_goals", None),
        ("Legend", "Complete 20 goals", 20, "completed_goals", None),

        # Progress milestones
        ("Progress Starter", "Reach 25% on any goal", 25, "progress", None),
        ("Halfway There", "Reach 50% progress", 50, "progress", None),
        ("Almost Done", "Reach 75% progress", 75, "progress", None),

        # Category milestones
        ("Health Hero", "Create 3 Health & Fitness goals", 3, "category", "Health & Fitness"),
        ("Learning Star", "Create 3 Learning goals", 3, "category", "Learning"),
        ("Career Builder", "Create 3 Career goals", 3, "category", "Career"),
        ("Money Smart", "Create 3 Finance goals", 3, "category", "Finance"),
        ("Relationship Pro", "Create 3 Relationships goals", 3, "category", "Relationships"),
        ("Hobbyist", "Create 3 Hobbies goals", 3, "category", "Hobbies"),
        ("Globetrotter", "Create 3 Travel goals", 3, "category", "Travel"),
        ("Personal Guru", "Create 3 Personal Development goals", 3, "category", "Personal Development"),
        ("Misc Master", "Create 3 Other goals", 3, "category", "Other"),
    ]

    for title, desc, val, mtype, category in milestones:
        Milestone.objects.update_or_create(
            title=title,
            defaults={
                "description": desc,
                "required_value": val,
                "milestone_type": mtype,
                "category": category,
            },
        )


class Migration(migrations.Migration):

    replaces = [
        ('goals', '0001_initial'),
        ('goals', '0002_milestone_usermilestone'),
        ('goals', '0004_rename_name_milestone_title_and_more'),
        ('goals', '0005_add_default_milestones'),
        ('goals', '0006_usermilestone_goals_userm_user_id_43715f_idx'),
        ('goals', '0007_alter_goal_category'),
        ('goals', '0008_milestone_category'),
        ('goals', '0009_alter_milestone_milestone_type'),
        ('goals', '0010_update_default_milestones'),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(
                    max_length=100,
                    choices=[
                        ('Personal Development', 'Personal Development'),
                        ('Health & Fitness', 'Health & Fitness'),
                        ('Learning', 'Learning'),
                        ('Career', 'Career'),
                        ('Finance', 'Finance'),
                        ('Relationships', 'Relationships'),
                        ('Hobbies', 'Hobbies'),
                        ('Travel', 'Travel'),
                        ('Other', 'Other'),
                    ],
                    default='Other'
                )),
                ('progress', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(
                    max_length=20,
                    choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')],
                    default='Not Started'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50, blank=True)),
                ('milestone_type', models.CharField(
                    max_length=50,
                    choices=[('total_goals', 'Total Goals'), ('completed_goals', 'Completed Goals'), ('progress', 'Progress'), ('category', 'Category')]
                )),
                ('required_value', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(
                    max_length=100,
                    choices=[
                        ('Personal Development', 'Personal Development'),
                        ('Health & Fitness', 'Health & Fitness'),
                        ('Learning', 'Learning'),
                        ('Career', 'Career'),
                        ('Finance', 'Finance'),
                        ('Relationships', 'Relationships'),
                        ('Hobbies', 'Hobbies'),
                        ('Travel', 'Travel'),
                        ('Other', 'Other'),
                    ],
                    blank=True,
                    null=True
                )),
            ],
        ),
        migrations.CreateModel(
            name='UserMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.Milestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'milestone')},
            },
        ),
        migrations.AddIndex(
            model_name='usermilestone',
            index=models.Index(fields=['user', 'milestone'], name='goals_userm_user_id_43715f_idx'),
        ),
        migrations.RunPython(create_default_milestones),
    ]
