# Generated by Django 5.2.6 on 2025-12-04 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_squashed_0010_update_default_milestones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='required_value',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='GoalProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.goal')),
            ],
        ),
    ]
